# Generated by Django 4.1.4 on 2022-12-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_tutorial_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='created',
        ),
    ]
